import type { GameCardItem } from "./game-card-item";

/** Danh sách game slot — `image` / `logo` trỏ vào `public/images/slot/`. */
export const SLOT_GAMES: GameCardItem[] = [
  {
    id: "slot-01",
    image: "/images/slot/slot01.webp",
    title: "프라그마틱 슬롯",
    logo: "/images/slot/logo/pragmatic_slot.webp",
    vendorId: "PragmaticPlay_Slot",
  },
  {
    id: "slot-02",
    image: "/images/slot/slot02.webp",
    title: "하바네로 슬롯",
    logo: "/images/slot/logo/habanero_slot.webp",
    vendorId: "Habanero",
  },
  {
    id: "slot-03",
    image: "/images/slot/slot03.webp",
    title: "BTG 슬롯",
    logo: "/images/slot/logo/btg_slot.webp",
    vendorId: "BTG",
  },
  {
    id: "slot-04",
    image: "/images/slot/slot04.webp",
    title: "릴렉스게이밍 슬롯",
    logo: "/images/slot/logo/relax_slot.webp",
    vendorId: "RelaxGaming",
  },
  {
    id: "slot-05",
    image: "/images/slot/slot05.webp",
    title: "넥스트스핀 슬롯",
    logo: "/images/slot/logo/nextspin_slot.webp",
    vendorId: "NextSpin",
  },
  {
    id: "slot-06",
    image: "/images/slot/slot06.webp",
    title: "플레이앤고 슬롯",
    logo: "/images/slot/logo/playngo_slot.webp",
    vendorId: "PlayNGo",
  },
  {
    id: "slot-07",
    image: "/images/slot/slot07.webp",
    title: "핵쏘우게이밍 슬롯",
    logo: "/images/slot/logo/hacksaw_slot.webp",
    vendorId: "HacksawGaming",
  },
  {
    id: "slot-08",
    image: "/images/slot/slot08.webp",
    title: "아바타UX 슬롯",
    logo: "/images/slot/logo/avatarux_slot.webp",
    vendorId: "AvatarUX",
  },
  {
    id: "slot-09",
    image: "/images/slot/slot09.webp",
    title: "부운고 슬롯",
    logo: "/images/slot/logo/bng_slot.webp",
    vendorId: "Booongo",
  },
  {
    id: "slot-10",
    image: "/images/slot/slot10.webp",
    title: "CQ9 슬롯",
    logo: "/images/slot/logo/cq9_slot.webp",
    vendorId: "CQ9",
  },
  {
    id: "slot-11",
    image: "/images/slot/slot11.webp",
    title: "PGSoft 슬롯",
    logo: "/images/slot/logo/pgsoft_slot.webp",
    vendorId: "PGSoft",
  },
  {
    id: "slot-12",
    image: "/images/slot/slot12.webp",
    title: "아시아게이밍 슬롯",
    logo: "/images/slot/logo/ag_slot.webp",
    vendorId: "AGAsia_Slot",
  },
  {
    id: "slot-13",
    image: "/images/slot/slot13.webp",
    title: "스카이윈드 슬롯",
    logo: "/images/slot/logo/skywind_slot.webp",
    vendorId: "Skywind_Slot",
  },
  {
    id: "slot-14",
    image: "/images/slot/slot14.webp",
    title: "릴플레이 슬롯",
    logo: "/images/slot/logo/reelplay_slot.webp",
    vendorId: "ReelPlay",
  },
  {
    id: "slot-15",
    image: "/images/slot/slot15.webp",
    title: "게임플레이 슬롯",
    logo: "/images/slot/logo/gpi_slot.webp",
    vendorId: "GamePlay",
  },
  {
    id: "slot-16",
    image: "/images/slot/slot16.webp",
    title: "드라군소프트 슬롯",
    logo: "/images/slot/logo/dragoonsoft_slot.webp",
    vendorId: "DragoonSoft",
  },
  {
    id: "slot-17",
    image: "/images/slot/slot17.webp",
    title: "심플플레이 슬롯",
    logo: "/images/slot/logo/simpleplay_slot.webp",
    vendorId: "SimplePlay",
  },
  {
    id: "slot-18",
    image: "/images/slot/slot18.webp",
    title: "슬롯밀 슬롯",
    logo: "/images/slot/logo/slotmill_slot.webp",
    vendorId: "Slotmill",
  },
  {
    id: "slot-19",
    image: "/images/slot/slot19.webp",
    title: "1X2게이밍 슬롯",
    logo: "/images/slot/logo/1x2_slot.webp",
    vendorId: "1X2Gaming",
  },
];
